services:

  postgres:
    image: postgres:16
    container_name: postgres-biblioteca
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: biblioteca_db
    ports:
      - "5432:5432"

  ms-libro:
    build: ./ms-libro
    container_name: ms-libro
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biblioteca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  ms-prestamo:
    build: ./ms-prestamo
    container_name: ms-prestamo
    depends_on:
      - postgres
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/biblioteca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin